#!/bin/bash
set -e

if ["$DEVELOP_SCHEMA_NAME" != "public"]; then
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$STAGING_DB_NAME" <<-EOSQL
  -- スキーマを作成
  CREATE SCHEMA "$DEVELOP_SCHEMA_NAME" AUTHORIZATION "$SUPERUSER_ROLE_NAME";

EOSQL
fi

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$STAGING_DB_NAME" <<-EOSQL
  -- 検証DBの開発スキーマ用のロールを作成
  CREATE ROLE "$DEVELOP_SCHEMA_ROLE_NAME" WITH LOGIN PASSWORD '$DEVELOP_SCHEMA_ROLE_PASSWORD';
  ALTER USER "$DEVELOP_SCHEMA_ROLE_NAME" SET search_path TO "$DEVELOP_SCHEMA_NAME";
  GRANT USAGE ON SCHEMA "$DEVELOP_SCHEMA_NAME" TO "$DEVELOP_SCHEMA_ROLE_NAME";
  REVOKE CREATE, TEMPORARY, TEMP ON DATABASE "$STAGING_DB_NAME" FROM "$DEVELOP_SCHEMA_ROLE_NAME";
  REVOKE CREATE ON SCHEMA "$DEVELOP_SCHEMA_NAME" FROM "$DEVELOP_SCHEMA_ROLE_NAME";

EOSQL
